fix(deps): downgrade Prisma from 7.3.0 to 6.6.0 to fix pathe/utils module error
Prisma 7.3.0 has a bug where it tries to require 'pathe/utils' which doesn't
exist in the CJS build. This causes database migrations to fail in production.

Downgrade to stable Prisma 6.x which doesn't have this issue:
- @prisma/client: 7.3.0 -> 6.6.0
- @prisma/adapter-pg: 7.3.0 -> 6.6.0
- @prisma/extension-accelerate: 3.0.1 -> 1.3.0
- prisma: 7.3.0 -> 6.6.0

Fixes deployment error: Cannot find module 'pathe/utils'